# Generated by Django 4.2.8 on 2024-01-28 14:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0023_bloodbankvendor'),
        ('blood_bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloodBank', to='vendor.bloodbankvendor')),
            ],
        ),
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BloodBankStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloodBankStock', to='blood_bank.bloodbank')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BloodGroup', to='blood_bank.bloodgroup')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BloodType', to='blood_bank.bloodtype')),
            ],
        ),
    ]
