# Generated by Django 4.2.8 on 2024-01-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0003_bloodbankstock_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='address',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
