# Generated by Django 4.2.8 on 2024-01-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0004_bloodbank_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbankstock',
            name='group',
        ),
        migrations.AddField(
            model_name='bloodbankstock',
            name='group',
            field=models.ManyToManyField(to='blood_bank.bloodgroup'),
        ),
    ]
