# Generated by Django 4.2.8 on 2024-01-28 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0005_remove_bloodbankstock_group_bloodbankstock_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbankstock',
            name='group',
        ),
        migrations.AddField(
            model_name='bloodbankstock',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BloodGroup', to='blood_bank.bloodgroup'),
        ),
    ]
