# Generated by Django 4.2.8 on 2024-01-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0007_alter_bloodbankstock_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbankstock',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
