# Generated by Django 4.2.8 on 2024-01-28 20:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0009_bloodbank_image_bloodbankstock_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_positive', models.BooleanField(default=False)),
                ('b_positive', models.BooleanField(default=False)),
                ('o_positive', models.BooleanField(default=False)),
                ('ab_positive', models.BooleanField(default=False)),
                ('a_negative', models.BooleanField(default=False)),
                ('b_negative', models.BooleanField(default=False)),
                ('o_negative', models.BooleanField(default=False)),
                ('ab_negative', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('uid', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_bank_stock', to='blood_bank.bloodbank')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_type', to='blood_bank.bloodtype')),
            ],
        ),
    ]
