# Generated by Django 4.2.8 on 2024-01-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
