# Generated by Django 4.2.8 on 2024-01-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0002_alter_labtest_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthconcern',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='concern/'),
        ),
    ]
