# Generated by Django 4.2.8 on 2024-01-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0003_healthconcern_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='total_tests_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
