# Generated by Django 4.2.8 on 2024-01-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0004_labtest_description_labtest_total_tests_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='related_tests',
            field=models.ManyToManyField(blank=True, to='labtests.labtest'),
        ),
    ]
