# Generated by Django 4.2.8 on 2024-01-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0006_labcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
