# Generated by Django 4.2.8 on 2024-01-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_productcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sub_category_images/'),
        ),
    ]
