# Generated by Django 4.2.8 on 2024-01-20 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_productreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='vendor',
            new_name='product',
        ),
    ]
