# Generated by Django 4.2.8 on 2024-01-21 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_rename_vendor_productreview_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbrand',
            name='uid',
        ),
    ]
