# Generated by Django 4.2.8 on 2024-01-21 09:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0014_productbrand_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrand',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
