# Generated by Django 4.2.8 on 2023-12-29 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_is_profile_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=60, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=1)], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=1)], verbose_name='last name'),
        ),
    ]
