# Generated by Django 4.2.8 on 2024-01-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_useraccount_email_alter_useraccount_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='office_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='pin_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='residential_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
