# Generated by Django 4.2.8 on 2024-02-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useraccount_office_address_useraccount_pin_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officeName', models.CharField(blank=True, null=True, verbose_name='name')),
                ('pincode', models.CharField(blank=True, null=True, verbose_name='pincode')),
                ('taluk', models.CharField(blank=True, null=True, verbose_name='taluk')),
                ('districtName', models.CharField(blank=True, null=True, verbose_name='districtName')),
                ('stateName', models.CharField(blank=True, null=True, verbose_name='stateName')),
            ],
        ),
    ]
